"""获取图片所需要的headers以及后续headers变量名"""
headers = {"Connection": "keep-alive", "Content-Type": "application/json; charset=UTF-8"}
count = 0
"""测试的ip地址是"""
ip = "192.168.1.61"
"""测试的path"""
create_path = "/api/create"
read_path = "/api/read"
delete_path = "/api/unlink"
edit_path = "/api/write"
name_get_path = "/api/name_get"
search_read_path = "/api/search_read"
load_model_path = "/api/load"
call_method_path = "/api/call_method"
upload_path = "/api/oss/upload"
onchange_path = "/api/onchange"
load_views_path = "/api/load_views"
default_get_path = "/api/default_get"
login_path = "/api/login"
image_path = "/api/validate/image"
read_group_path = "/api/read_group"
call_path = "/api/call"
getUserInfo_path = "/api/getUserInfo"
